### ISSUE TITLE
正常运行中突然报错，这个是啥情况

### ISSUE THREAD

**Issue by glimjoe** [zas023/JdBuyer#23]
2022-12-15 09:03:16,482 INFO: 登录成功
Traceback (most recent call last):
  File "C:\Users\~\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\~\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\~\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\~\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\temp\JdBuyer-main\JdBuyer.py", line 115, in <module>
    buyer.buyItemInStock(skuId, areaId, skuNum, stockInterval,
  File "C:\temp\JdBuyer-main\JdBuyer.py", line 76, in buyItemInStock
    self.session.fetchItemDetail(skuId)
  File "C:\temp\JdBuyer-main\JdSession.py", line 169, in fetchItemDetail
    resp = self.getItemDetail(skuId).json()
  File "C:\Users\~\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

尝试打印getItemDetail方法中调用京东接口的返回值，发现是{'code': 200,'limit': 1}

**Comment by anysoft** [comment]
被限制访问了。应该是账号被限了。因为一直调用接口频率过高，所以对账号进行限制了。至于多久能解封，这个就不好说了。
正确用法是短时间内刷5秒的库存查询间隔还好，如果要长时间挂机刷，那么库存频率得提升到15~30s左右。

**Comment by glimjoe** [comment]
> 被限制访问了。应该是账号被限了。因为一直调用接口频率过高，所以对账号进行限制了。至于多久能解封，这个就不好说了。 正确用法是短时间内刷5秒的库存查询间隔还好，如果要长时间挂机刷，那么库存频率得提升到15~30s左右。

麻了，我开的2秒一次。。。那我等解封改到20秒好了

**Comment by asd8855** [comment]
换个IP,后者wifi切换成热点就好了

**Comment by WGwangguan** [comment]
换了 ip 也不得行了

**Comment by anysoft** [comment]
> 换了 ip 也不得行了

封的账号，别频繁请求，对jd来说算恶意请求的。
