### ISSUE TITLE
不能用了吧？

### ISSUE THREAD

**Issue by webdage** [zas023/JdBuyer#28]
F:\jd\JdBuyer-main>python JdBuyer.py
2022-12-15 22:35:39,021 INFO: 登录成功
Traceback (most recent call last):
  File "F:\jd\JdBuyer-main\JdBuyer.py", line 115, in <module>
    buyer.buyItemInStock(skuId, areaId, skuNum, stockInterval,
  File "F:\jd\JdBuyer-main\JdBuyer.py", line 75, in buyItemInStock
    self.session.fetchItemDetail(skuId)
  File "F:\jd\JdBuyer-main\JdSession.py", line 169, in fetchItemDetail
    resp = self.getItemDetail(skuId).json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\YanYonghang\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\YanYonghang\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\YanYonghang\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\YanYonghang\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by EightyOliveira** [comment]
File "JdBuyer.py", line 115, in <module>
    buyer.buyItemInStock(skuId, areaId, skuNum, stockInterval,
  File "JdBuyer.py", line 75, in buyItemInStock
    self.session.fetchItemDetail(skuId)
  File "D:\JdBuyer-main\JdSession.py", line 169, in fetchItemDetail
    resp = self.getItemDetail(skuId).json()
  File "C:\Users\python\lib\site-packages\requests\models.py", line 976, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by ZealBear** [comment]
#23 参考这个
