### ISSUE TITLE
登录成功后报错

### ISSUE THREAD

**Issue by KawhiKevin** [zas023/JdBuyer#49]
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\requests\models.py", line 972, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Learn\JDBuyBuy\JdBuyer_KangYuan_JiuAn\JdBuyer.py", line 115, in <module>
    buyer.buyItemInStock(skuId, areaId, skuNum, stockInterval,
  File "E:\Learn\JDBuyBuy\JdBuyer_KangYuan_JiuAn\JdBuyer.py", line 75, in buyItemInStock
    self.session.fetchItemDetail(skuId)
  File "E:\Learn\JDBuyBuy\JdBuyer_KangYuan_JiuAn\JdSession.py", line 169, in fetchItemDetail
    resp = self.getItemDetail(skuId).json()
  File "C:\Program Files\Python39\lib\site-packages\requests\models.py", line 976, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by zhouzhili** [comment]
一样这个错误，怎么解决呢

**Comment by doubleJJJJ** [comment]
同问，昨天还是可以下单的，今天登录就显示这个错误了

**Comment by minweiS** [comment]
出错的可以看下PR

**Comment by qing666888** [comment]
resp = self.getItemDetail(skuId).json()  这句获取到商品信息后，转json报错了

**Comment by bjx451278** [comment]
触发反爬了
