### ISSUE TITLE
requests.exceptions.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

### ISSUE THREAD

**Issue by shuyuncong0** [zas023/JdBuyer#9]
PS D:\workplace\JdBuyer-main> python JdBuyer.py
2022-10-30 18:14:12,605 INFO: 登录成功
Traceback (most recent call last):
  File "D:\javaDev\PythonDev\lib\site-packages\requests\models.py", line 972, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\javaDev\PythonDev\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\javaDev\PythonDev\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\javaDev\PythonDev\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "JdBuyer.py", line 115, in <module>
    buyer.buyItemInStock(skuId, areaId, skuNum, stockInterval,
  File "JdBuyer.py", line 75, in buyItemInStock
    self.session.fetchItemDetail(skuId)
  File "D:\workplace\JdBuyer-main\JdSession.py", line 169, in fetchItemDetail
    resp = self.getItemDetail(skuId).json()
  File "D:\javaDev\PythonDev\lib\site-packages\requests\models.py", line 976, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by neotaburiss** [comment]
今天下午用的时候还是好好的， 后面突然变成这个错误怎么都不行了。。。

有可能是查询过多，被京东屏蔽了？

**Comment by DDDybala** [comment]
我也出现这个问题了

**Comment by songmuhan** [comment]
+1

**Comment by xkwy521** [comment]
+1 我也出现了

**Comment by AxisRay** [comment]
```
2022-12-13 00:57:33,210 INFO: 登录成功
{'code':200,'limit':1}
{'code':200,'limit':1}
Traceback (most recent call last):
 ```
被屏蔽了，超限制了

**Comment by EndoSakura** [comment]
很尴尬

**Comment by WGwangguan** [comment]
刚才下下来，一登录就提示这个，有什么好的解决办法么？
